# --- IDENTIFIANTS DU PROJET ---
# Utilisation de "projet-stage" tel que tu l'as nommé dans SonarQube
sonar.projectKey=projet-ozonewell
sonar.projectName=projeto zonewell
sonar.projectVersion=1.0

# --- CONFIGURATION DE LA CONNEXION ET DU TOKEN ---
# URL par défaut de ton serveur SonarQube local
sonar.host.url=http://localhost:9000
# Ton Token personnel que tu as fourni
sonar.login=sqp_ef2da2f09cc9d3bb68bef8e9bf7de92326779397

# --- CONFIGURATION DES SOURCES ---
# On analyse le dossier src (là où se trouve ton code React)
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Définition du langage (JavaScript/React)
sonar.language=js
sonar.javascript.file.suffixes=.js,.jsx

# --- EXCLUSIONS (Très important pour la rapidité) ---
# On ignore les dossiers qui ne contiennent pas ton code personnel
sonar.exclusions=node_modules/**, dist/**, .vite/**, public/**, **/*.test.jsx, **/*.test.js, vite.config.js

# --- ENVIRONNEMENT ---
# Indique à Sonar que le code s'exécute dans un navigateur
sonar.javascript.environments=browser